In [1]:
import torch as t

### Ways to initialize tensors:
<ul>
    <p>zeros, ones, eye, t.Tensor(2,3)</p>
    <p>linspace(begin,last,count)</p>
    <p>arange(begin,last,stride)</p>
    <p>t.randn(2,3)</p>
    <p>t.randperm(length)</p>
<ul>    


In [2]:
t.linspace(1,12,5)

tensor([ 1.0000,  3.7500,  6.5000,  9.2500, 12.0000])

tensor.view to reshape tensors. Not inplace operation. One copy.

squeeze(), unsqueeze()

In [13]:
a = t.arange(0,6)
b = a.view(2,3)

In [16]:
a[0] = 10
print(a.view(2,3))
print(b, b.shape)

tensor([[10,  1,  2],
        [ 3,  4,  5]])
tensor([[10,  1,  2],
        [ 3,  4,  5]]) torch.Size([2, 3])


In [19]:
b.unsqueeze(1)

tensor([[[10,  1,  2]],

        [[ 3,  4,  5]]])

In [21]:
b.unsqueeze(-2)

torch.Size([2, 1, 3])

---
Squeeze()

In [23]:
c = b.view(1,1,1,2,3)
c.squeeze(1)

tensor([[[[10,  1,  2],
          [ 3,  4,  5]]]])

In [24]:
c.squeeze() #crash all dimensions with 1

tensor([[10,  1,  2],
        [ 3,  4,  5]])

---
index

In [30]:
a = t.randn(3,4)
print(a)

tensor([[-0.7744,  0.5060, -0.9724,  0.3852],
        [-0.3093,  2.0376,  0.1977, -1.6281],
        [ 0.1491, -0.8150, -0.2205,  0.8988]])


In [31]:
print(a[0:1,:2])
print(a[0:1,0:2])
print(a[0,:2])

tensor([[-0.7744,  0.5060]])
tensor([[-0.7744,  0.5060]])
tensor([-0.7744,  0.5060])


In [40]:
a>0
print((a>0).type())

torch.BoolTensor


In [38]:
a[t.LongTensor([0,2])] #1st and 3rd rows

tensor([[-0.7744,  0.5060, -0.9724,  0.3852],
        [ 0.1491, -0.8150, -0.2205,  0.8988]])

In [42]:
a = t.arange(0,16).view(4,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [44]:
b = a[t.arange(4),t.arange(4)]
b

tensor([ 0,  5, 10, 15])

In [55]:
index = t.LongTensor([[0,1,2,3]])
index

tensor([[0, 1, 2, 3]])

In [57]:
a.gather(0,index)

tensor([[ 0,  5, 10, 15]])

---
### Tensor 类型

In [59]:
a = t.Tensor(3,4)
a

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
t.set_default_tensor_type('torch.LongTensor')

TypeError: only floating-point types are supported as the default type

In [64]:
b = t.LongTensor(3,4)
b

tensor([[137438953592, 137438953533, 197568495732, 472446402633],
        [360777252980, 472446402661, 476741369971, 171798691954],
        [390842024027, 188978561072, 188978561073, 188978561074]])

In [66]:
c = b.float()
c

tensor([[1.3744e+11, 1.3744e+11, 1.9757e+11, 4.7245e+11],
        [3.6078e+11, 4.7245e+11, 4.7674e+11, 1.7180e+11],
        [3.9084e+11, 1.8898e+11, 1.8898e+11, 1.8898e+11]])

In [70]:
d = b.new(2,3) #用b的类型创建全为0的对应形状
d

tensor([[0, 0, 0],
        [0, 0, 0]])

In [71]:
a = t.arange(0,6).view(2,3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [72]:
t.clamp(a,min =2,max =4)

tensor([[2, 2, 2],
        [3, 4, 4]])

In [76]:
b = t.ones(2,3).long()
b.sum(dim = 0, keepdim = True)

tensor([[2, 2, 2]])

In [78]:
b.sum(dim =0)

tensor([2, 2, 2])

一点小对比， torch的tensor和numpy的ndarray

In [90]:
import numpy as np
mat = np.ones((2,3))
print("mat sum is :",mat.sum(axis =0))
print(type(mat))

mat sum is : [2. 2. 2.]
<class 'numpy.ndarray'>


In [87]:
mat0 = t.ones(2,3)
print("mat0 sum is:", mat0.sum(dim = 0))

mat0 sum is: tensor([2., 2., 2.])


---


cumsum是累加，dim=1就是沿着行累加。

In [92]:
mat0

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [93]:
mat0.cumsum(dim =1)

tensor([[1., 2., 3.],
        [1., 2., 3.]])

---
---
## Comparison

gt/lt/le/eq/ne

topk

sort

max/min

In [95]:
a = t.linspace(0,15,6).view(3,2)

In [97]:
_,pred =t.max(a,dim =1)

---
内部结构

In [102]:
a = np.arange(0,6).reshape(2,3)
b = t.from_numpy(a)

In [103]:
b.storage()

 0
 1
 2
 3
 4
 5
[torch.IntStorage of size 6]

In [106]:
c = b.view(3,2)

In [108]:
print(b)
print(c)

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)
tensor([[0, 1],
        [2, 3],
        [4, 5]], dtype=torch.int32)


In [110]:
id(b.storage()) == id(c.storage())

True

In [112]:
print(c.data_ptr(),b.data_ptr())

2043809575344 2043809575344


Tensor保存和加载简单，t.save(), t.load()可指定使用pickle模块。还可以存储在GPU上。
向量化后的计算很多是在底层C++实现，大幅缩短计算时间。
大多数t.function都有一个参数out，这是产生的结果在这个out指定的tensor中
t.set_num_threads限制所占用CPU的线程数
t.set_printoptions可以用来设置输出格式和精度(precision)